import { serve } from 'bun';

import indexHtml from './src/index.html';

const server = serve({
  routes: {
    '/': indexHtml
  },
  development: true,
  fetch(req) {
    const url = new URL(req.url);
    // Serve static files from public directory
    const publicPath = `public${url.pathname}`;
    const publicFile = Bun.file(publicPath);
    if (publicFile.size > 0) {
      return new Response(publicFile);
    }

    // Serve dist files from root (generated by bun build)
    if (url.pathname.startsWith('/dist/')) {
      const distFile = Bun.file(`.${url.pathname}`);
      if (distFile.size > 0) {
        return new Response(distFile);
      }
    }

    return new Response('Not Found', { status: 404 });
  }
});

console.log(`🚀 Server running on ${server.url.toString()}`);
